#
# Create:
# $ conda env create --prefix .tmnre_env --file environment.yml
#
# Update:
# $ conda env update --prefix .tmnre_env --file environment.yml --prune
#
# Activate:
# $ conda activate ~/path/to/tmnre/.tmnre_env
name: tmnre_env

channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia

dependencies:
  - "python >= 3.6.0"
  - "pytorch = 1.8.1"
  - "cudatoolkit = 11.1"
  - jupyter
  - jupyterlab
  - matplotlib
  - notebook
  - pillow
  - scikit-learn
  - scipy
  - numpy
  - zarr>=2.5.0
  - numcodecs>=0.7.2
  - tqdm>=4.46.0
  - scikit-learn>=0.23.2
  - dask[complete]>=2021.3.0
  - pandas
  - seaborn
  - toolz
  - pip
  - pip:
    - "pyknos>=0.14.2"
    - "pyro-ppl>=1.3.1"
    - -e "./remote/sbi[dev]"
    - -e "./remote/sbibm"
    - -e "./remote/swyft"
    - -e "."
