[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tmnre/__version__.py"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["remote/swyft/swyft", "remote/sbibm/sbibm", "tmnre"]
