# @package _group_
name: tmnre
run: tmnre.algorithms.tmnre.run
device: ${hardware.device}
params:
  num_weighted_samples: 1000000
  initial_simulation_factor: 0.3
  compute_2d_marginals: ${analysis.compute_2d_marginals}
  device: ${hardware.device}
  simulation_batch_size: 1000
  max_rounds: 10
  new_simulation_factor: 1.0
  new_simulation_term: 0
  convergence_ratio: 0.8
  neural_net: resnet
  hidden_features: 50
  batch_size: 128
  validation_size: 0.10
  early_stopping_patience: 20
  max_epochs: 300
  lr: 1e-2
  reduce_lr_factor: 0.1
  reduce_lr_patience: 5
  online_z_score_head: False
  online_z_score_tail: True
  nworkers: 4
